# File _config.yml
# Contiene le definizioni delle variabili globali disponibili a livello di sito.
# NB: le variabili definite in questo file _config.yml avviene anteponendo il prefisso site.
#     Esempio: site.name site.timezone ecc. ecc.
#
# IMPORTANTE: una variabile definita qui può far riferimento ad una variabile definita in uno dei file di language, come ad esempio it.yml
#             In questo caso, si potrà usare una traduzione.

name: global.website.name
highlighter: pygments
#url:
#    it: https://www.cryptoteam.it
#    en: https://www.cryptoteam.it

include: [.htaccess,__Analytics*]
exclude: [bin,jobs,README.md]

timezone: UTC

#languages: ["it", "it", "en"]
languages: ["it", "it"]

description: global.website.description

excerpt_separator: N/A-------N/A... Workaround for https://github.com/mojombo/jekyll/issues/1401

### Disabled for now. Default is nice.
# permalink: :categories/:year-:month-:day-:title.html

# La navigazione da includere, ogni cosa inserita qui è
# una chiave per trovare la pagina corretta. Il nome e i titoli dei link
# sono presi da ciascuna pagina stessa, così come la relazione con la
# pagina a monte.

# Ogni nome deve essere unico e la pagina deve avere lo stesso nome.
# Controlla l'area all'interno del blocco --- e l'attributo del nome.
# Stesso nome, stessa pagina.
# Gli URL qui sono anche gli url costruiti di default.
# La personalizzazione lavora in modalità differente.

sitenavigation:
  - name: Proteggersi
    secondarynav:
        - name: Proteggersi
  - name: CosaFacciamo
    secondarynav:
        - name: CosaFacciamo
        - name: Protezione Dati
        - name: Controllo Accessi
        - name: Cloud in House
        - name: Progetti Personalizzati
  - name: Offerta
    secondarynav:
        - name: Offerta
        - name: Crittografia
        - name: Piattaforma PKI
        - name: IDS
        - name: Cancellazione Sicura
  - name: Normativa
    secondarynav:
        - name: Normativa
        - name: Adempimenti
        - name: Notizie
        - name: Archivio News
  - name: ChiSiamo
    secondarynav:
        - name: ChiSiamo
        - name: Privacy
        - name: Newsletter
        - name: Contatti
#  - name: :External
#    title: Blog
#    url: https://blog.cryptoteam.it/
